services:
  - type: web
    name: farmerpee
    env: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: farmerpee-db
          property: connectionString

databases:
  - name: farmerpee-db
    databaseName: farmerpee
    user: farmerpee
